drop table if exists deals;

create table deals (
  id text primary key,
  title text not null,
  description text,
  category text not null,
  price numeric not null,
  "originalPrice" numeric not null,
  "discountPercent" numeric not null,
  condition text not null,
  "storeName" text not null,
  "storeLocation" jsonb not null,
  "shippingAvailable" boolean,
  "onlineReferralRate" numeric,
  "referralEarningType" text,
  "referralEarningValue" numeric,
  "originalProductUrl" text,
  "imageUrl" text,
  "popularityScore" numeric,
  comps jsonb
);

alter table deals enable row level security;
create policy "Allow public read access" on deals for select using (true);

insert into deals (id, title, description, category, price, "originalPrice", "discountPercent", condition, "storeName", "storeLocation", "shippingAvailable", "onlineReferralRate", "referralEarningType", "referralEarningValue", "originalProductUrl", "imageUrl", "popularityScore", comps) values (
    'deal-01',
    'Apple iPad Pro 11" M4 (256GB, Wi-Fi)',
    'Open box item in pristine condition. Unopened accessories, standard Apple warranty applies. Box has minor label scuffs.',
    'Electronics',
    749,
    999,
    25,
    'Open Box - Pristine',
    'Best Buy Outlet',
    '{"lat":34.0672,"lng":-118.26570000000001,"city":"Los Angeles","state":"CA","address":"11301 Pico Blvd, Los Angeles, CA 90064","storeName":"Best Buy Outlet #188"}',
    true,
    4,
    'percentage',
    30,
    'https://www.bestbuy.com/ipad-pro-m4',
    'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&auto=format&fit=crop&q=80',
    94,
    '[{"id":"comp-01a","title":"iPad Pro 11\" M4 (256GB) - Open Box","storeName":"Target Liquidators","price":729,"originalPrice":999,"condition":"Box Damaged - New","distanceMiles":3.2,"driveTimeMins":8,"lat":34.0802,"lng":-118.2557,"address":"8985 Venice Blvd, Los Angeles, CA 90034","savingsMessage":"Saves $20 extra, but 8 mins further drive."},{"id":"comp-01b","title":"iPad Pro 11\" M4 (256GB) - Grade A","storeName":"Micro Center Clearance","price":760,"originalPrice":999,"condition":"Refurbished","distanceMiles":1.8,"driveTimeMins":4,"lat":34.0572,"lng":-118.2587,"address":"1100 S Westmoreland Ave, Los Angeles, CA 90006","savingsMessage":"4 mins closer but costs $11 more."}]'
  );
insert into deals (id, title, description, category, price, "originalPrice", "discountPercent", condition, "storeName", "storeLocation", "shippingAvailable", "onlineReferralRate", "referralEarningType", "referralEarningValue", "originalProductUrl", "imageUrl", "popularityScore", comps) values (
    'deal-02',
    'DeWalt 20V MAX XR Brushless 6-Tool Combo Kit',
    'Excess contractor stock liquidation. Complete heavy-duty tool kit. Packaging has tear-throughs, but all tools are brand new with full manufacturer seals.',
    'Tools & Home',
    389,
    649,
    40,
    'Box Damaged - New',
    'Home Depot Liquidation Center',
    '{"lat":41.853100000000005,"lng":-87.5948,"city":"Chicago","state":"IL","address":"1300 S Clinton St, Chicago, IL 60607","storeName":"Home Depot Liquidation #094"}',
    false,
    6,
    'percentage',
    23.34,
    'https://www.homedepot.com/dewalt-combo-kit',
    'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=600&auto=format&fit=crop&q=80',
    88,
    '[{"id":"comp-02a","title":"DeWalt 20V Brushless Combo Kit","storeName":"Lowe''s Outlet Depot","price":369,"originalPrice":649,"condition":"Open Box - Excellent","distanceMiles":2.1,"driveTimeMins":5,"lat":41.8661,"lng":-87.6118,"address":"2639 N Elston Ave, Chicago, IL 60647","savingsMessage":"Saves $20 and is 5 mins away! Highly recommended."},{"id":"comp-02b","title":"DeWalt 20V 5-Tool Kit (No bag)","storeName":"Harbor Freight Salvage","price":310,"originalPrice":549,"condition":"Clearance Pallet","distanceMiles":6.4,"driveTimeMins":14,"lat":41.8331,"lng":-87.5748,"address":"3200 S Kedzie Ave, Chicago, IL 60623","savingsMessage":"Cheaper, but missing 1 tool and 14 mins away."}]'
  );
insert into deals (id, title, description, category, price, "originalPrice", "discountPercent", condition, "storeName", "storeLocation", "shippingAvailable", "onlineReferralRate", "referralEarningType", "referralEarningValue", "originalProductUrl", "imageUrl", "popularityScore", comps) values (
    'deal-03',
    'Samsung Bespoke 4-Door French Door Refrigerator',
    'High-end smart refrigerator with beverage center. Floor model clearance. Minor hairline scratch on left steel panel (less than 1 inch). Completely tested and fully functional.',
    'Appliances',
    1499,
    3199,
    53,
    'Open Box - Excellent',
    'Sears Hometown Outlet',
    '{"lat":29.7924,"lng":-95.3848,"city":"Houston","state":"TX","address":"10900 Gulf Fwy, Houston, TX 77034","storeName":"Sears Liquidation Houston"}',
    false,
    5,
    'flat',
    75,
    'https://www.samsung.com/bespoke-refrigerator',
    'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&auto=format&fit=crop&q=80',
    97,
    '[{"id":"comp-03a","title":"Samsung French Door Fridge - Blemished","storeName":"Appliance Direct Outlet","price":1399,"originalPrice":3199,"condition":"Box Damaged - New","distanceMiles":4.8,"driveTimeMins":11,"lat":29.7754,"lng":-95.4078,"address":"4112 Old Spanish Trail, Houston, TX 77021","savingsMessage":"Save an extra $100! 11 mins drive."},{"id":"comp-03b","title":"Samsung Bespoke Smart Fridge","storeName":"Best Buy Warehouse Outlet","price":1650,"originalPrice":3199,"condition":"Open Box - Pristine","distanceMiles":1.2,"driveTimeMins":3,"lat":29.7984,"lng":-95.3748,"address":"5130 Richmond Ave, Houston, TX 77056","savingsMessage":"Pristine condition and 3 mins away, but costs $151 more."}]'
  );
insert into deals (id, title, description, category, price, "originalPrice", "discountPercent", condition, "storeName", "storeLocation", "shippingAvailable", "onlineReferralRate", "referralEarningType", "referralEarningValue", "originalProductUrl", "imageUrl", "popularityScore", comps) values (
    'deal-04',
    'Sony WH-1000XM5 Noise Canceling Headphones',
    'Slightly worn retail display unit. Fully cleaned, sanitized, and tested. Sounds incredible. Comes in standard hard-shell travel case. USB-C charging cord included.',
    'Electronics',
    219,
    399,
    45,
    'Refurbished',
    'Sony Outlet Store',
    '{"lat":32.7647,"lng":-96.815,"city":"Dallas","state":"TX","address":"2200 N Central Expy, Dallas, TX 75204","storeName":"Sony Refurbish Dallas"}',
    true,
    8,
    'percentage',
    17.52,
    'https://www.sony.com/wh1000xm5',
    'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80',
    91,
    '[{"id":"comp-04a","title":"Sony WH-1000XM5 Headphones - Clean","storeName":"Micro Center Clearance","price":239,"originalPrice":399,"condition":"Open Box - Excellent","distanceMiles":1.5,"driveTimeMins":3,"lat":32.771699999999996,"lng":-96.80799999999999,"address":"13929 N Central Expy, Dallas, TX 75243","savingsMessage":"Excellent open box grade, 3 mins drive, costs $20 more."},{"id":"comp-04b","title":"Sony WH-1000XM5 - Box Only Damaged","storeName":"Liquidators Depot","price":199,"originalPrice":399,"condition":"Box Damaged - New","distanceMiles":5.1,"driveTimeMins":12,"lat":32.7417,"lng":-96.822,"address":"4220 LBJ Freeway, Dallas, TX 75244","savingsMessage":"Saves $20, but 12 mins further out."}]'
  );
insert into deals (id, title, description, category, price, "originalPrice", "discountPercent", condition, "storeName", "storeLocation", "shippingAvailable", "onlineReferralRate", "referralEarningType", "referralEarningValue", "originalProductUrl", "imageUrl", "popularityScore", comps) values (
    'deal-05',
    'Mega Liquidation Pallet: Mixed Home Goods & Kitchen Tools',
    'Premium Amazon overstock liquidation pallet. Packed with estimated 45-60 items including air fryers, instant pots, cookware sets, and smart scales. Perfect for resellers.',
    'Liquidation Pallets',
    499,
    1850,
    73,
    'Clearance Pallet',
    'USA Pallet Liquidation Corp',
    '{"lat":33.773,"lng":-84.406,"city":"Atlanta","state":"GA","address":"1420 Marietta Blvd NW, Atlanta, GA 30318","storeName":"USA Pallet Depot Atlanta"}',
    false,
    10,
    'flat',
    50,
    'https://www.palletbid.com/amazon-home-pallet',
    'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=600&auto=format&fit=crop&q=80',
    96,
    '[{"id":"comp-05a","title":"Tier 1 Amazon Kitchen Pallet","storeName":"ATL Wholesale Pallets","price":450,"originalPrice":1600,"condition":"Clearance Pallet","distanceMiles":4.5,"driveTimeMins":9,"lat":33.761,"lng":-84.433,"address":"500 Fulton Industrial Blvd SW, Atlanta, GA 30336","savingsMessage":"Saves $49. 9 mins drive, slightly smaller box density."},{"id":"comp-05b","title":"Premium Electronics Liquidation Pallet","storeName":"Bulq Atlanta Depot","price":650,"originalPrice":2400,"condition":"Clearance Pallet","distanceMiles":3.1,"driveTimeMins":6,"lat":33.794000000000004,"lng":-84.4,"address":"1200 Lake Mirror Rd, Atlanta, GA 30349","savingsMessage":"Higher-value electronics items. 6 mins away, costs $151 more."}]'
  );
insert into deals (id, title, description, category, price, "originalPrice", "discountPercent", condition, "storeName", "storeLocation", "shippingAvailable", "onlineReferralRate", "referralEarningType", "referralEarningValue", "originalProductUrl", "imageUrl", "popularityScore", comps) values (
    'deal-06',
    'Crate & Barrel Wells Leather Swivel Chair',
    'Floor inventory model in Chestnut brown top-grain leather. Rotates 360 degrees. Frame is structurally flawless. Extremely light rubbing wear on the lower back piping.',
    'Furniture',
    520,
    1199,
    57,
    'Open Box - Excellent',
    'Crate & Barrel Clearance Hub',
    '{"lat":25.7467,"lng":-80.1698,"city":"Miami","state":"FL","address":"7300 SW 57th Ave, Miami, FL 33143","storeName":"Crate & Barrel Outlet #405"}',
    false,
    7,
    'percentage',
    36.4,
    'https://www.crateandbarrel.com/wells-leather-chair',
    'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=600&auto=format&fit=crop&q=80',
    84,
    '[{"id":"comp-06a","title":"Crate & Barrel Wells Chair (Camel)","storeName":"West Elm Clearance Depot","price":490,"originalPrice":1199,"condition":"Box Damaged - New","distanceMiles":1.4,"driveTimeMins":3,"lat":25.7437,"lng":-80.1838,"address":"3201 Buena Vista Blvd, Miami, FL 33127","savingsMessage":"Saves $30 and only 3 mins away. camel leather instead of chestnut."}]'
  );
insert into deals (id, title, description, category, price, "originalPrice", "discountPercent", condition, "storeName", "storeLocation", "shippingAvailable", "onlineReferralRate", "referralEarningType", "referralEarningValue", "originalProductUrl", "imageUrl", "popularityScore", comps) values (
    'deal-07',
    'LG UltraGear 34" OLED Curved Gaming Monitor',
    'Box-damaged stock item. Outer cardboard had forklift puncture, but screen panel, electronic boards, and calibration tests are completely unaffected. Brand new accessory box.',
    'Electronics',
    649,
    1199,
    46,
    'Box Damaged - New',
    'Best Buy Liquidation Store',
    '{"lat":40.7308,"lng":-74.021,"city":"New York","state":"NY","address":"529 5th Ave, New York, NY 10017","storeName":"Best Buy Midtown Liquidation"}',
    true,
    5,
    'percentage',
    32.45,
    'https://www.bestbuy.com/lg-ultragear-34-oled',
    'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600&auto=format&fit=crop&q=80',
    95,
    '[{"id":"comp-07a","title":"LG 34\" Curved OLED Monitor","storeName":"B&H Photo Video Used Dept","price":680,"originalPrice":1199,"condition":"Open Box - Excellent","distanceMiles":1.1,"driveTimeMins":4,"lat":40.7368,"lng":-74.011,"address":"420 9th Ave, New York, NY 10001","savingsMessage":"No cardboard damage but costs $31 more."},{"id":"comp-07b","title":"LG UltraGear 34\" OLED - Mint","storeName":"Adorama Used Store","price":630,"originalPrice":1199,"condition":"Refurbished","distanceMiles":2.3,"driveTimeMins":8,"lat":40.717800000000004,"lng":-74.031,"address":"42 W 18th St, New York, NY 10011","savingsMessage":"Saves $19 but is 8 mins away in heavy Manhattan traffic."}]'
  );
insert into deals (id, title, description, category, price, "originalPrice", "discountPercent", condition, "storeName", "storeLocation", "shippingAvailable", "onlineReferralRate", "referralEarningType", "referralEarningValue", "originalProductUrl", "imageUrl", "popularityScore", comps) values (
    'deal-08',
    'Breville Barista Touch Espresso Machine',
    'Customer return open box item. Disassembled, fully steam-cleaned, scale removed, and fully detailed. 100% operation rate. Comes with milk pitcher, portafilter, and starter cleaning tablets.',
    'Appliances',
    599,
    999,
    40,
    'Open Box - Excellent',
    'Seattle Coffee Outlet',
    '{"lat":47.5942,"lng":-122.3171,"city":"Seattle","state":"WA","address":"2700 Duwamish Ave S, Seattle, WA 98134","storeName":"Seattle Liquidation Coffee Depot"}',
    true,
    6,
    'percentage',
    35.94,
    'https://www.breville.com/barista-touch',
    'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80',
    92,
    '[{"id":"comp-08a","title":"Breville Barista Touch (Black Truffle)","storeName":"Williams Sonoma Outlet","price":649,"originalPrice":999,"condition":"Open Box - Pristine","distanceMiles":3.5,"driveTimeMins":8,"lat":47.5812,"lng":-122.2971,"address":"University Village, Seattle, WA 98105","savingsMessage":"Costs $50 more but has original premium black finish."},{"id":"comp-08b","title":"Breville Barista Touch Espresso - Box Wear","storeName":"Sur La Table Clearance","price":579,"originalPrice":999,"condition":"Box Damaged - New","distanceMiles":1.1,"driveTimeMins":3,"lat":47.6012,"lng":-122.3211,"address":"84 Pine St, Seattle, WA 98101","savingsMessage":"Saves $20 and is 3 mins closer! Highly recommended."}]'
  );
insert into deals (id, title, description, category, price, "originalPrice", "discountPercent", condition, "storeName", "storeLocation", "shippingAvailable", "onlineReferralRate", "referralEarningType", "referralEarningValue", "originalProductUrl", "imageUrl", "popularityScore", comps) values (
    'deal-09',
    'DeWalt 12" Double Bevel Compound Miter Saw',
    'Open-box item in pristine condition. Never used to cut wood. Display piece. Blade, instructions, dust collection bag, and material clamp included.',
    'Tools & Home',
    299,
    599,
    50,
    'Open Box - Pristine',
    'Home Depot Outlet Store',
    '{"lat":34.0272,"lng":-118.21170000000001,"city":"Los Angeles","state":"CA","address":"5600 Sunset Blvd, Los Angeles, CA 90028","storeName":"Home Depot Sunset Outlet"}',
    false,
    5,
    'flat',
    20,
    'https://www.homedepot.com/dewalt-miter-saw',
    'https://images.unsplash.com/photo-1534224039826-c7a0dea0e66a?w=600&auto=format&fit=crop&q=80',
    89,
    '[{"id":"comp-09a","title":"DeWalt 12\" Miter Saw - Damaged Box","storeName":"Lowe''s Liquidation Depot","price":285,"originalPrice":599,"condition":"Box Damaged - New","distanceMiles":2.5,"driveTimeMins":6,"lat":34.0372,"lng":-118.2287,"address":"12148 Burbank Blvd, Los Angeles, CA 91607","savingsMessage":"Saves $14 and only 6 mins away."}]'
  );
insert into deals (id, title, description, category, price, "originalPrice", "discountPercent", condition, "storeName", "storeLocation", "shippingAvailable", "onlineReferralRate", "referralEarningType", "referralEarningValue", "originalProductUrl", "imageUrl", "popularityScore", comps) values (
    'deal-10',
    'Dyson V15 Detect Cordless Vacuum Cleaner',
    'Refurbished vacuum directly by Dyson technicians. Completely checked and working at full suction. Replaced with clean filter, multi-surface brush roll, and mini motorized brush.',
    'Appliances',
    349,
    749,
    53,
    'Refurbished',
    'Dyson Direct Refurb Hub',
    '{"lat":41.9061,"lng":-87.6478,"city":"Chicago","state":"IL","address":"640 N La Salle Dr, Chicago, IL 60654","storeName":"Dyson Center Chicago"}',
    true,
    8,
    'percentage',
    27.92,
    'https://www.dyson.com/v15-detect',
    'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=600&auto=format&fit=crop&q=80',
    93,
    '[{"id":"comp-10a","title":"Dyson V15 Detect - Open Box","storeName":"Target Liquidation Store","price":380,"originalPrice":749,"condition":"Open Box - Excellent","distanceMiles":1.4,"driveTimeMins":3,"lat":41.893100000000004,"lng":-87.6348,"address":"1154 S Clark St, Chicago, IL 60605","savingsMessage":"Slightly higher price ($31 more) but original pristine box."}]'
  );
